colorscheme default
set guifont=Input\ Mono\ Narrow:h18
set guioptions=

" https://stackoverflow.com/a/4945278
inoremap <D-s> <ESC>:w<CR>i
nnoremap <D-s> :w<CR>

let g:nerdtree_tabs_autoclose = 0

" https://github.com/neovim/neovim/issues/2656#issuecomment-212377296
set mouse=a
let g:NERDTreeMouseMode=3

