
let vimdir = expand('<sfile>:p:h')

" Basics
set nocompatible
set nobackup
set noswapfile
set noerrorbells
set novisualbell
let &runtimepath=vimdir . ',' . $VIMRUNTIME
set backspace=2
set shortmess+=I
set fileformat=unix
set textwidth=80
set laststatus=2

" 256 colours
set t_Co=256


syntax on
filetype indent plugin on
au BufEnter,BufNewFile,BufRead *.md        setlocal filetype=markdown
au BufEnter,BufNewFile,BufRead Vagrantfile setlocal filetype=ruby
au BufEnter,BufNewFile,BufRead *.less      setlocal filetype=less
au BufEnter,BufNewFile,BufRead *.yml       setlocal filetype=yaml
au BufEnter,BufNewFile,BufRead *.json      setlocal filetype=json


" Disables: Entering Ex mode.  Type "visual" to go to Normal mode. 
map Q <nop>


" Wildmenu
set wildmenu
set wildignore+=.git
set wildignore+=.svn
set wildignore+=*.bmp
set wildignore+=*.gif
set wildignore+=*.jpg
set wildignore+=*.jpeg
set wildignore+=*.png
set wildignore+=*.swf
set wildignore+=*.DS_Store


" Folding
set nofoldenable


" Indentation
set autoindent
set smartindent


" Search
set ignorecase
set incsearch


" Display
set cursorcolumn
set cursorline
set nowrap
set number
set ruler
set viminfo=""


" No help, please
noremap  <F1> <nop>
inoremap <F1> <nop>


" Reselect visual block after indent/outdent 
vnoremap < <gv
vnoremap > >gv


" Easy split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


" Make Y behave like other capitals
map Y y$


" Improve up/down movement on wrapped lines
nnoremap j gj
nnoremap k gk


" Keep highlighted search result in middle of screen
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz
nnoremap <silent> g# g#zz


" Easier Markdown underlining
nnoremap <leader>= :set fo-=a<CR>yypv$r=<CR>:set fo += a<CR>
nnoremap <leader>- :set fo-=a<CR>yypv$r-<CR>:set fo +=a<CR>


" Visual guidelines for common maximum widths
set colorcolumn=81,121


" Simple mappings for built-in Vim stuff
nnoremap <leader>h  :set invhlsearch<CR>
nnoremap <leader>i  :exec ":hi " . synIDattr(synID(line("."), col("."), 1), "name")<CR>
nnoremap <leader>m  :make<CR>
nnoremap <leader>q  :quit!<CR>
nnoremap <leader>w  :write<CR>
nnoremap <leader>wq :write<CR>:quit!<CR>


" Filetype mappings for quick syntax-highlighting changes
nnoremap <leader>css  :set filetype=css<CR>
nnoremap <leader>html :set filetype=html<CR>
nnoremap <leader>php  :set filetype=php<CR>
nnoremap <leader>sql  :set filetype=sql<CR>


" Getting sick of hitting ,php for every badly named PHP file
map <F12> :set filetype=php<CR>


" Custom function mappings
nnoremap <leader><tab> :call InvertTabstop()<CR>


" Pathogen
call pathogen#infect()
call pathogen#helptags()


" Solarized
colorscheme solarized
set background=dark


" Command T
nnoremap <leader>t :CommandT<CR>
let g:CommandTMaxFiles=40000


" php-doc 
nnoremap <leader>pd :call PhpDocSingle()<CR>


" vcscommand 
nnoremap <leader>va :VCSAdd<CR>
nnoremap <leader>vc :VCSCommit<CR>
nnoremap <leader>vd :VCSVimDiff<CR>
nnoremap <leader>vl :VCSLog<CR>
nnoremap <leader>vu :VCSUpdate<CR>
nnoremap <leader>vr :VCSRevert<CR>


" NERDTree
let NERDTreeMinimalUI=1
let NERDChristmasTree=1



