" Tell Vim where we are
let vimdir = "~/.dotfiles/vim"
let &runtimepath=vimdir . ',' . $VIMRUNTIME

" Turn off the bad things
set nocompatible
set nobackup
set noswapfile
set noerrorbells
set novisualbell
set backspace=2
set nowrap
set nofoldenable

" The space bar makes a good <leader> key
let mapleader=" "

" Syntax highlighting is best highlighting
syntax on
syntax sync minlines=256
set synmaxcol=256

" Turn on the good things
filetype indent plugin on
set autoindent
set smartindent

" Some very boring things
set shortmess+=I
set fileformat=unix
set textwidth=80
set laststatus=2

" Update Vim's obsolete file recognition
au BufEnter,BufNewFile,BufRead *.scss setlocal filetype=css
au BufEnter,BufNewFile,BufRead *.md setlocal filetype=markdown
au BufEnter,BufNewFile,BufRead *.less setlocal filetype=less
au BufEnter,BufNewFile,BufRead *.yml setlocal filetype=yaml
au BufEnter,BufNewFile,BufRead *.json setlocal filetype=json

" Go away, ex mode
map Q <nop>

" There really is nothing wild about this menu
set wildmenu
set wildignore+=.git
set wildignore+=.svn
set wildignore+=*.bmp
set wildignore+=*.gif
set wildignore+=*.jpg
set wildignore+=*.jpeg
set wildignore+=*.png
set wildignore+=*.swf
set wildignore+=*.DS_Store

" Search like a modern editor
set ignorecase
set incsearch

" Fill the screen with a constant torrent of information
set number
set ruler

" No help, please
noremap  <F1> <nop>
inoremap <F1> <nop>

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Make Y behave like other capitals
map Y y$

" Keep highlighted search result in middle of screen
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz
nnoremap <silent> g# g#zz

" Simple mappings for built-in Vim stuff
nnoremap <leader>q  :quit!<CR>
nnoremap <leader>w  :write<CR>
nnoremap <leader>wq :write<CR>:quit!<CR>

" Easier Markdown underlining
nnoremap <leader>= :set fo-=a<CR>yypv$r=<CR>:set fo += a<CR>
nnoremap <leader>- :set fo-=a<CR>yypv$r-<CR>:set fo +=a<CR>

" Visual guidelines for common maximum widths
set colorcolumn=81,121

" Simple mappings for built-in Vim stuff
nnoremap <leader>q  :quit!<CR>
nnoremap <leader>w  :write<CR>
nnoremap <leader>wq :write<CR>:quit!<CR>

" 256 colours should be enough for anyone
set t_Co=256
set background=dark
colorscheme solarized

